var exampleData = {
    "queryCost": 1,
    "latitude": 45.0983,
    "longitude": -93.4419,
    "resolvedAddress": "Maple Grove, MN, United States",
    "address": "maple grove",
    "timezone": "America/Chicago",
    "tzoffset": -5,
    "description": "Warming up with no rain expected.",
    "days": [
     {
      "datetime": "2022-06-13",
      "datetimeEpoch": 1655096400,
      "tempmax": 80.1,
      "tempmin": 67.9,
      "temp": 72.4,
      "feelslikemax": 83.1,
      "feelslikemin": 67.9,
      "feelslike": 72.6,
      "dew": 66.7,
      "humidity": 82.8,
      "precip": 0.1,
      "precipprob": 100,
      "precipcover": 12.5,
      "preciptype": [
       "rain"
      ],
      "snow": 0,
      "snowdepth": 0,
      "windgust": 35.5,
      "windspeed": 15.4,
      "winddir": 118.1,
      "pressure": 1004.5,
      "cloudcover": 50.5,
      "visibility": 9.6,
      "solarradiation": 137,
      "solarenergy": 11.8,
      "uvindex": 8,
      "severerisk": 15,
      "sunrise": "05:26:13",
      "sunriseEpoch": 1655115973,
      "sunset": "21:01:51",
      "sunsetEpoch": 1655172111,
      "moonphase": 0.49,
      "conditions": "Rain, Partially cloudy",
      "description": "Partly cloudy throughout the day with morning rain.",
      "icon": "rain",
      "stations": [
       "HPN02",
       "KFCM",
       "KMSP",
       "KMIC"
      ],
      "source": "comb",
      "hours": [
       {
        "datetime": "12:00:00",
        "datetimeEpoch": 1655139600,
        "temp": 73.1,
        "feelslike": 73.1,
        "humidity": 83.72,
        "dew": 67.8,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": [
         "rain"
        ],
        "windgust": 19.7,
        "windspeed": 10.7,
        "winddir": 112,
        "pressure": 1005,
        "visibility": 9.8,
        "cloudcover": 51.5,
        "solarradiation": 107,
        "solarenergy": 0.4,
        "uvindex": 1,
        "severerisk": 10,
        "conditions": "Partially cloudy",
        "icon": "partly-cloudy-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "13:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 71,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "14:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 70,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "15:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 69,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "16:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 68,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "17:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 67,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "18:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 66,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "19:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 65,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "20:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 64,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "21:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 63,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       },
       {
        "datetime": "22:00:00",
        "datetimeEpoch": 1655143200,
        "temp": 62,
        "feelslike": 72,
        "humidity": 83.49,
        "dew": 66.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 12.5,
        "windspeed": 6.9,
        "winddir": 81,
        "pressure": 1003.8,
        "visibility": 9.9,
        "cloudcover": 6.1,
        "solarradiation": 153,
        "solarenergy": 0.6,
        "uvindex": 2,
        "severerisk": 5,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "obs"
       }
      ]
     },
     {
        "datetime": "2022-06-14",
        "datetimeEpoch": 1655096400,
        "tempmax": 80.1,
        "tempmin": 67.9,
        "temp": 72.4,
        "feelslikemax": 83.1,
        "feelslikemin": 67.9,
        "feelslike": 72.6,
        "dew": 66.7,
        "humidity": 82.8,
        "precip": 0.1,
        "precipprob": 100,
        "precipcover": 12.5,
        "preciptype": [
         "rain"
        ],
        "snow": 0,
        "snowdepth": 0,
        "windgust": 35.5,
        "windspeed": 15.4,
        "winddir": 118.1,
        "pressure": 1004.5,
        "cloudcover": 50.5,
        "visibility": 9.6,
        "solarradiation": 137,
        "solarenergy": 11.8,
        "uvindex": 8,
        "severerisk": 15,
        "sunrise": "05:26:13",
        "sunriseEpoch": 1655115973,
        "sunset": "21:01:51",
        "sunsetEpoch": 1655172111,
        "moonphase": 0.49,
        "conditions": "Rain, Partially cloudy",
        "description": "Partly cloudy throughout the day with morning rain.",
        "icon": "rain",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "comb",
        "hours": [
         {
          "datetime": "12:00:00",
          "datetimeEpoch": 1655139600,
          "temp": 73.1,
          "feelslike": 73.1,
          "humidity": 83.72,
          "dew": 67.8,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": [
           "rain"
          ],
          "windgust": 19.7,
          "windspeed": 10.7,
          "winddir": 112,
          "pressure": 1005,
          "visibility": 9.8,
          "cloudcover": 51.5,
          "solarradiation": 107,
          "solarenergy": 0.4,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
           "HPN02",
           "KFCM",
           "KMSP",
           "KMIC"
          ],
          "source": "obs"
         },
         {
          "datetime": "13:00:00",
          "datetimeEpoch": 1655143200,
          "temp": 72,
          "feelslike": 72,
          "humidity": 83.49,
          "dew": 66.7,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 12.5,
          "windspeed": 6.9,
          "winddir": 81,
          "pressure": 1003.8,
          "visibility": 9.9,
          "cloudcover": 6.1,
          "solarradiation": 153,
          "solarenergy": 0.6,
          "uvindex": 2,
          "severerisk": 5,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
           "HPN02",
           "KFCM",
           "KMSP",
           "KMIC"
          ],
          "source": "obs"
         }
        ]
       },
       {
        "datetime": "2022-06-15",
        "datetimeEpoch": 1655096400,
        "tempmax": 80.1,
        "tempmin": 67.9,
        "temp": 72.4,
        "feelslikemax": 83.1,
        "feelslikemin": 67.9,
        "feelslike": 72.6,
        "dew": 66.7,
        "humidity": 82.8,
        "precip": 0.1,
        "precipprob": 100,
        "precipcover": 12.5,
        "preciptype": [
         "rain"
        ],
        "snow": 0,
        "snowdepth": 0,
        "windgust": 35.5,
        "windspeed": 15.4,
        "winddir": 118.1,
        "pressure": 1004.5,
        "cloudcover": 50.5,
        "visibility": 9.6,
        "solarradiation": 137,
        "solarenergy": 11.8,
        "uvindex": 8,
        "severerisk": 15,
        "sunrise": "05:26:13",
        "sunriseEpoch": 1655115973,
        "sunset": "21:01:51",
        "sunsetEpoch": 1655172111,
        "moonphase": 0.49,
        "conditions": "Rain, Partially cloudy",
        "description": "Partly cloudy throughout the day with morning rain.",
        "icon": "rain",
        "stations": [
         "HPN02",
         "KFCM",
         "KMSP",
         "KMIC"
        ],
        "source": "comb",
        "hours": [
         {
          "datetime": "12:00:00",
          "datetimeEpoch": 1655139600,
          "temp": 73.1,
          "feelslike": 73.1,
          "humidity": 83.72,
          "dew": 67.8,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": [
           "rain"
          ],
          "windgust": 19.7,
          "windspeed": 10.7,
          "winddir": 112,
          "pressure": 1005,
          "visibility": 9.8,
          "cloudcover": 51.5,
          "solarradiation": 107,
          "solarenergy": 0.4,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
           "HPN02",
           "KFCM",
           "KMSP",
           "KMIC"
          ],
          "source": "obs"
         },
         {
          "datetime": "13:00:00",
          "datetimeEpoch": 1655143200,
          "temp": 72,
          "feelslike": 72,
          "humidity": 83.49,
          "dew": 66.7,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 12.5,
          "windspeed": 6.9,
          "winddir": 81,
          "pressure": 1003.8,
          "visibility": 9.9,
          "cloudcover": 6.1,
          "solarradiation": 153,
          "solarenergy": 0.6,
          "uvindex": 2,
          "severerisk": 5,
          "conditions": "Clear",
          "icon": "clear-day",
          "stations": [
           "HPN02",
           "KFCM",
           "KMSP",
           "KMIC"
          ],
          "source": "obs"
         }
        ]
       }
    ],
    "alerts": [
     {
      "event": "Excessive Heat Warning",
      "headline": "Excessive Heat Warning issued June 13 at 3:16AM CDT until June 14 at 8:00PM CDT by NWS Minneapolis",
      "description": "...EXCESSIVE HEAT WARNING IN EFFECT FROM 11 AM TO 8 PM CDT\nTUESDAY...\n* WHAT...Dangerously hot conditions with heat index values up to\n103 expected.\n* WHERE...Hennepin, Anoka, Ramsey, Washington, Carver, Scott and\nDakota Counties.\n* WHEN...From 11 AM to 8 PM CDT Tuesday.\n* IMPACTS...Extreme heat and humidity will significantly\nincrease the potential for heat related illnesses, particularly\nfor those working or participating in outdoor activities.",
      "ends": "2022-06-15T01:00:00",
      "endsEpoch": 1655254800,
      "onset": "2022-06-14T16:00:00",
      "onsetEpoch": 1655222400,
      "id": "NOAA-NWS-ALERTS-MN1263FA75BA00.ExcessiveHeatWarning.1263FA9326D0MN.MPXNPWMPX.729315514bf88901345067155fa5c50d",
      "language": "en",
      "link": "https://alerts.weather.gov/cap/wwacapget.php?x=MN1263FA75BA00.ExcessiveHeatWarning.1263FA9326D0MN.MPXNPWMPX.729315514bf88901345067155fa5c50d"
     }
    ],
    "stations": {
     "HPN02": {
      "distance": 2459,
      "latitude": 45.118,
      "longitude": -93.428,
      "useCount": 0,
      "id": "HPN02",
      "name": "Maple Grove MN US",
      "quality": 0,
      "contribution": 0
     },
     "KMSP": {
      "distance": 29929,
      "latitude": 44.88,
      "longitude": -93.22,
      "useCount": 0,
      "id": "KMSP",
      "name": "KMSP",
      "quality": 100,
      "contribution": 0
     },
     "KFCM": {
      "distance": 29874,
      "latitude": 44.83,
      "longitude": -93.45,
      "useCount": 0,
      "id": "KFCM",
      "name": "KFCM",
      "quality": 100,
      "contribution": 0
     },
     "KMIC": {
      "distance": 7880,
      "latitude": 45.07,
      "longitude": -93.35,
      "useCount": 0,
      "id": "KMIC",
      "name": "KMIC",
      "quality": 100,
      "contribution": 0
     },
     "MN087": {
      "distance": 678,
      "latitude": 45.096,
      "longitude": -93.45,
      "useCount": 0,
      "id": "MN087",
      "name": "Maple Grove I-94 Mile Post 217",
      "quality": 0,
      "contribution": 0
     }
    },
    "currentConditions": {
     "datetime": "17:50:01",
     "datetimeEpoch": 1655160601,
     "temp": 75.6,
     "feelslike": 75.6,
     "humidity": 77,
     "dew": 67.9,
     "precip": 0,
     "precipprob": null,
     "snow": 0,
     "snowdepth": 0,
     "preciptype": null,
     "windgust": null,
     "windspeed": 8.4,
     "winddir": 72,
     "pressure": 1003.9,
     "visibility": 12.4,
     "cloudcover": 100,
     "solarradiation": 123,
     "solarenergy": 0.4,
     "uvindex": 1,
     "conditions": "Overcast",
     "icon": "cloudy",
     "stations": [
      "KFCM",
      "MN087",
      "KMIC"
     ],
     "sunrise": "05:26:13",
     "sunriseEpoch": 1655115973,
     "sunset": "21:01:51",
     "sunsetEpoch": 1655172111,
     "moonphase": 0.49
    }
   }

   var londonData = {
      "queryCost": 1,
      "latitude": 51.5064,
      "longitude": -0.12721,
      "resolvedAddress": "London, England, United Kingdom",
      "address": "london",
      "timezone": "Europe/London",
      "tzoffset": 1,
      "description": "Cooling down with a chance of rain Saturday & Sunday.",
      "days": [
       {
        "datetime": "2022-06-15",
        "datetimeEpoch": 1655247600,
        "tempmax": 77.8,
        "tempmin": 53.1,
        "temp": 67,
        "feelslikemax": 77.8,
        "feelslikemin": 53.1,
        "feelslike": 67,
        "dew": 49.9,
        "humidity": 57.1,
        "precip": 0,
        "precipprob": 0,
        "precipcover": 0,
        "preciptype": null,
        "snow": 0,
        "snowdepth": 0,
        "windgust": 15.4,
        "windspeed": 6,
        "winddir": 142.9,
        "pressure": 1018.8,
        "cloudcover": 52.5,
        "visibility": 13.9,
        "solarradiation": 325.7,
        "solarenergy": 28.3,
        "uvindex": 9,
        "severerisk": 10,
        "sunrise": "04:42:51",
        "sunriseEpoch": 1655264571,
        "sunset": "21:19:27",
        "sunsetEpoch": 1655324367,
        "moonphase": 0.51,
        "conditions": "Partially cloudy",
        "description": "Partly cloudy throughout the day.",
        "icon": "partly-cloudy-day",
        "stations": [
         "EGWU",
         "EGLL",
         "EGLC"
        ],
        "source": "comb",
        "hours": [
         {
          "datetime": "12:00:00",
          "datetimeEpoch": 1655290800,
          "temp": 74,
          "feelslike": 74,
          "humidity": 42.1,
          "dew": 49.5,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.3,
          "windspeed": 3.6,
          "winddir": 162.9,
          "pressure": 1019,
          "visibility": 15,
          "cloudcover": 54.7,
          "solarradiation": 850,
          "solarenergy": 3.1,
          "uvindex": 9,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
         },
         {
          "datetime": "13:00:00",
          "datetimeEpoch": 1655294400,
          "temp": 75.8,
          "feelslike": 75.8,
          "humidity": 39.12,
          "dew": 49.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 11.4,
          "windspeed": 3.8,
          "winddir": 177.3,
          "pressure": 1019,
          "visibility": 15,
          "cloudcover": 77,
          "solarradiation": 847,
          "solarenergy": 3,
          "uvindex": 8,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
         }
        ]
       }
      ],
      "alerts": [],
      "stations": {
       "EGWU": {
        "distance": 20850,
        "latitude": 51.55,
        "longitude": -0.42,
        "useCount": 0,
        "id": "EGWU",
        "name": "EGWU",
        "quality": 50,
        "contribution": 0
       },
       "EGLC": {
        "distance": 12300,
        "latitude": 51.5,
        "longitude": 0.05,
        "useCount": 0,
        "id": "EGLC",
        "name": "EGLC",
        "quality": 50,
        "contribution": 0
       },
       "EGLL": {
        "distance": 22564,
        "latitude": 51.48,
        "longitude": -0.45,
        "useCount": 0,
        "id": "EGLL",
        "name": "EGLL",
        "quality": 50,
        "contribution": 0
       },
       "D5621": {
        "distance": 11192,
        "latitude": 51.535,
        "longitude": 0.028,
        "useCount": 0,
        "id": "D5621",
        "name": "DW5621 Upton Park UK",
        "quality": 0,
        "contribution": 0
       }
      },
      "currentConditions": {
       "datetime": "02:36:06",
       "datetimeEpoch": 1655256966,
       "temp": 57.7,
       "feelslike": 57.7,
       "humidity": 71.1,
       "dew": 48.5,
       "precip": 0,
       "precipprob": null,
       "snow": 0,
       "snowdepth": 0,
       "preciptype": null,
       "windgust": null,
       "windspeed": 3.8,
       "winddir": 74,
       "pressure": 1018.7,
       "visibility": 6.2,
       "cloudcover": 0,
       "solarradiation": 0,
       "solarenergy": null,
       "uvindex": 0,
       "conditions": "Clear",
       "icon": "clear-night",
       "stations": [
        "EGWU",
        "D5621",
        "EGLC"
       ],
       "sunrise": "04:42:51",
       "sunriseEpoch": 1655264571,
       "sunset": "21:19:27",
       "sunsetEpoch": 1655324367,
       "moonphase": 0.51
      }
     }


   module.exports = {exampleData, londonData};